// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9S_v310TxH8t9_dFzAoXihnfJeENqL8o',
    appId: '1:461367772402:web:3d4902c4eee6ebdbb63c6b',
    messagingSenderId: '461367772402',
    projectId: 'authe-af1a4',
    authDomain: 'authe-af1a4.firebaseapp.com',
    storageBucket: 'authe-af1a4.appspot.com',
    measurementId: 'G-ZDY95QN6L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO84SpE-93PH9UjDzkAiT82acWGQcLzFE',
    appId: '1:461367772402:android:a2ad9a553dd7bfefb63c6b',
    messagingSenderId: '461367772402',
    projectId: 'authe-af1a4',
    storageBucket: 'authe-af1a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDquESLWlHEuTGi2JsZMrjH0-TQNhAPZXI',
    appId: '1:461367772402:ios:bc74c7b0297e02cbb63c6b',
    messagingSenderId: '461367772402',
    projectId: 'authe-af1a4',
    storageBucket: 'authe-af1a4.appspot.com',
    androidClientId: '461367772402-0d3bpa1d8n8kkhs6imt7v4ttlu4uvndk.apps.googleusercontent.com',
    iosClientId: '461367772402-lriftkebdrked1qbvl18iiqhn703ab2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDquESLWlHEuTGi2JsZMrjH0-TQNhAPZXI',
    appId: '1:461367772402:ios:bc74c7b0297e02cbb63c6b',
    messagingSenderId: '461367772402',
    projectId: 'authe-af1a4',
    storageBucket: 'authe-af1a4.appspot.com',
    androidClientId: '461367772402-0d3bpa1d8n8kkhs6imt7v4ttlu4uvndk.apps.googleusercontent.com',
    iosClientId: '461367772402-lriftkebdrked1qbvl18iiqhn703ab2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
